version: '3.8'

services:
  spring-app:
    build:
      context: .                      # Contexte de construction du Dockerfile
      dockerfile: Dockerfile          # Nom du Dockerfile
    image: amenidrira/spring_app
    ports:
      - "8086:8086"                   # Mapping du port pour l'application
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""   # Mot de passe MySQL
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8086                # Port du serveur
    depends_on:
      - mysql                          # Démarrer MySQL avant Spring Boot
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Fichier de configuration pour Prometheus
    networks:
      - app-network
    depends_on:
      - spring-app  # Démarrer Prometheus après l'application Spring Boot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app-network
    depends_on:
      - prometheus   # Démarrer Grafana après Prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql-data:
  grafana-storage:

networks:
  app-network:
